### ISSUE TITLE
Bug: Member profile information is wrong, and cant be updated

### ISSUE THREAD

**Issue by xEPIx** [justarrived/just-match-web#367] opened 2017-03-02 13:34 UTC
https://app.justarrived.se/users/78

The above is my profile page, i found different information than what i created first time, even different address.
When i try to update the information it saves it successfully, but when refreshing the page it default back to the old information.

**Comment by buren** [comment] 2017-03-03 09:39
The reason the address got changed could have been when we imported data from WGTRM.. I've just tested our current version of the app and it works as intended (for me).

@xEPIx could you try updating your address again? 👼  and if it works you can close this issue :)

Thanks for reporting! 👑

**Comment by xEPIx** [comment] 2017-03-03 14:21
Thank You, Works as intended. 👑

**Closed as completed** 2017-03-03 14:21 UTC
